package com.medicai.pillpal.domain.enumeration;

/**
 * The Form enumeration.
 */
public enum Form {
    AEROSOL, BAR, CAPSULE, CLOTH, CONCENTRATE, CREAM, DISC, DRESSING, ELIXIR, EMULSION, ENEMA, FIBER, FILM, FOR_SOLUTION, FOR_SUSPENSION, GAS, GEL, GRANULE, GUM, IMPLANT, INHALANT, INJECTABLE, INJECTION, INSERT, INTRAUTERINE_DEVICE, JELLY, LIQUID, LOTION, LOTION_SHAMPOO, N_A, OIL, OIL_DROPS, OINTMENT, PASTE, PASTILLE, PATCH, PELLET, PELLETS, POWDER, POWDER_FOR_ORAL_SOLUTION, RING, SHAMPOO, SOAP, SOLUTION, SOLUTION_DROPS, SOLUTION_FOR_SLUSH, SPONGE, SPRAY, SUPPOSITORY, SUSPENSION, SUSPENSION_DROPS, SWAB, SYRINGE, SYRUP, SYSTEM, TABLET, TAMPON, TAPE, TROCHE_LOZENGE, UNKNOWN, VIAL
}
