package com.medicai.pillpal.domain.enumeration;

/**
 * The RoutsOfAdministration enumeration.
 */
public enum RoutsOfAdministration {
    BLOCK_INFILTRATION, BUCCAL, DENTAL, DIALYSIS, DISINFECTANT_BARN, DISINFECTANT, DISINFECTANT_DOMESTIC, DISINFECTANT_FOOD_PREMISES, DISINFECTANT_HOSPITAL_HC_FACILITIES, DISINFECTANT_INSTITUTIONAL_INDUSTRIAL, DISINFECTANT_MEDICAL_INSTRUMENTS, EPIDURAL, EXTRACORPOREAL, INFILTRATION, INHALATION, INSTILLATION, INTRA_AMNIOTIC, INTRA_ARTERIAL, INTRA_ARTICULAR, INTRABRANCHIAL, INTRABURSAL, INTRACARDIAC, INTRACAUDAL, INTRACAVERNOSAL, INTRACEREBROVENTRICULAR, INTRACERVICAL, INTRACORONARY, INTRACRANIAL, INTRADERMAL, INTRADISCAL, INTRAGANGLIONAL, INTRAINTESTINAL, INTRALESIONAL, INTRAMAMMARY, INTRAMUSCULAR, INTRAOCULAR, INTRAPERITONEAL, INTRAPLEURAL, INTRAPULMONARY, INTRARUMINAL, INTRASPINAL, INTRASYNOVIAL, INTRATENDINOUS, INTRATHECAL, INTRATHORACIC, INTRATRACHEAL, INTRAUTERINE, INTRAVASCULAR, INTRAVENOUS, INTRAVENTRICULAR, INTRAVITREAL, INTUBING, IRRIGATION, NASAL, NASOGASTRIC, NERVE_BLOCK, OPHTHALMIC, ORAL, OTIC, PARENTERAL_UNSPECIFIED, PERCUTANEOUS, PERIARTICULAR, PERIOSTEAL, RECTAL, RETROBULBAR, SOFT_TISSUE_INJECTION, SUBARACHNOIDAL, SUBCUTANEOUS, SUBGINGIVAL, SUBLINGUAL, SUBMUCOSAL, SURGICAL, TOPICAL, TOPICAL_COMMERCIAL, TOPICAL_FOOD_PREMISES, TOPICAL_HOSPITAL_HC_FACILITIES, TOPICAL_HOUSEHOLD, TRANSDERMAL, UDDER_WASH, URETHRAL, VAGINAL
}
